apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alloy
  namespace: logging-demo
  labels:
    app: alloy
spec:
  selector:
    matchLabels:
      app: alloy
  template:
    metadata:
      labels:
        app: alloy
    spec:
      serviceAccountName: alloy
      containers:
        - name: alloy
          image: grafana/alloy:v1.11.3
          args:
            - run
            - --storage.path=/var/lib/alloy/data
            - --server.http.listen-addr=0.0.0.0:12345
            - /etc/alloy/alloy.alloy
          volumeMounts:
            - name: alloy-config
              mountPath: /etc/alloy
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: alloy-data
              mountPath: /var/lib/alloy
      volumes:
        - name: alloy-config
          configMap:
            name: alloy-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: alloy-data
          emptyDir: {}

