apiVersion: v1
kind: Pod
metadata:
  name: crashloop-test
  namespace: monitoring-demo
  labels:
    app: crashloop-test
spec:
  containers:
    - name: crash
      image: busybox:1.36
      command: ["sh", "-c", "echo 'crashing...'; exit 1"]
  restartPolicy: Always
