apiVersion: v1
kind: Pod
metadata:
  name: fake-target
  namespace: monitoring-demo
  labels:
    app: fake-target
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9091"
    prometheus.io/path: "/metrics"
spec:
  containers:
    - name: pushgateway
      image: prom/pushgateway:v1.8.0
      ports:
        - containerPort: 9091

