apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-exporter
  namespace: monitoring-demo
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: monitoring-demo
  labels:
    app: node-exporter
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      hostNetwork: true
      hostPID: true
      serviceAccountName: node-exporter
      tolerations:
        - operator: "Exists"
      containers:
        - name: node-exporter
          image: quay.io/prometheus/node-exporter:v1.10.2
          args:
            - --path.rootfs=/host
            - --collector.filesystem.ignored-mount-points=^/(sys|proc|dev|run|var/lib/docker/.+|var/lib/kubelet/.+)($|/)
            - --collector.filesystem.ignored-fs-types=^overlay$|^tmpfs$|^cgroup2?$
          ports:
            - name: metrics
              containerPort: 9100
              hostPort: 9100
          volumeMounts:
            - name: root
              mountPath: /host
              readOnly: true
      volumes:
        - name: root
          hostPath:
            path: /
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: monitoring-demo
  labels:
    app: node-exporter
spec:
  clusterIP: None
  selector:
    app: node-exporter
  ports:
    - name: metrics
      port: 9100
      targetPort: 9100
