apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: tracing-demo
data:
  otel-collector.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:

    exporters:
      # Exportador OTLP hacia Tempo
      otlp/tempo:
        endpoint: "tempo.tracing-demo.svc.cluster.local:4317"
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/tempo]

