apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: monitoring-demo
data:
  general-rules.yaml: |
    groups:
      - name: general.rules
        rules:
          - alert: PodRestarting
            expr: sum by (namespace,pod) (increase(kube_pod_container_status_restarts_total[10m])) > 3
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: "Pod {{ $labels.pod }} reiniciando"
              description: "El pod {{ $labels.pod }} en {{ $labels.namespace }} ha reiniciado >3 veces en 10m."

          - alert: TargetDown
            expr: up == 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Target {{ $labels.instance }} caído"
              description: "Prometheus no puede hacer scrape de {{ $labels.job }} en {{ $labels.instance }}."
  disk-rules.yaml: |
    groups:
      - name: disk.rules
        rules:
          - alert: NodeDiskUsageHigh
            expr: 100 * (1 - node_filesystem_avail_bytes{fstype!~"tmpfs|overlay"}
                            / node_filesystem_size_bytes{fstype!~"tmpfs|overlay"}) > 85
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "Uso de disco alto en {{ $labels.instance }}"
              description: "El filesystem {{ $labels.device }} está por encima del 85%."
