apiVersion: v1
kind: Pod
metadata:
  name: nginx-pvc
spec:
  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts:
        - name: demo-storage
          mountPath: /usr/share/nginx/html
  volumes:
    - name: demo-storage
      persistentVolumeClaim:
        claimName: demo-pvc
